config/routes.rb
Dispensary::Application.routes.draw do
  devise_for :users

  resources :organizations, :only => [:new, :show, :create, :index] do
    resources :apps, :only => [:new, :create, :show, :index] do
      resources :builds, :only => [:new, :create, :show, :download, :install] do
        member do
          get :download
          get :install, :defaults => { :format => 'plist' }
        end
      end
    end
  end

  root :to => "welcome#index"
end

app/models/app.rb
class App < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  has_many :builds
  belongs_to :organization

  def latest_build
    builds.last
  end
end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :app
  mount_uploader :bundle, BundleUploader
  validates_presence_of :bundle, :message => "You must attach an iOS bundle"
  validates_length_of [:version, :display_name, :bundle_identifier], :minimum => 1,
    :too_short => "your bundle seems to be corrupt or missing data, please verify your project has been built correctly and try again"
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :owner, :class_name => "User"
  has_many :apps
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :organizations, :foreign_key => "owner_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  respond_to :html

  expose(:organization)
  expose(:app)
  expose(:apps) {App.all}
  
  def create
    if app.save
      flash[:notice] = "Successfully created #{app.name}"
      respond_with(organization, app)
    else
      render :new
    end
  end

  def index
  end
end

app/controllers/builds_controller.rb
Mime::Type.register "text/xml", :plist

class BuildsController < ApplicationController
  respond_to :html, :plist

  expose(:app)
  expose(:build)

  def create
    build.app_id = app.id
    if build.save
      flash[:notice] = "Build Added!"
      redirect_to app
    else
      render :new
    end
  end

  def download
    send_file build.bundle.path
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  respond_to :html

  expose(:organization) 
  expose(:organizations) {current_user.organizations}

  def create
    organization.owner = current_user
    if organization.save
      flash[:notice] = 'Successfully created organization'
      respond_with(organization)
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apps/new.html.haml
%h1 Creating New Application

= form_for [organization, app] do |f|
  = f.label :name
  %small= error_message_on app, :name
  = f.text_field :name
  = f.submit "Create Application" 

app/views/apps/show.html.haml
%h1 Application: #{app.name}
- if app.latest_build
  %h3= link_to "Download latest build", app.latest_build.bundle.url
  %h3= link_to "Install latest build", "itms-services://?action=download-manifest&url=#{install_organization_app_build_url(organization, app, app.latest_build, :format => 'plist').gsub(/localhost/, IP_ADDRESS)}.plist"
- else
  %h2= link_to "Add Build", new_organization_app_build_path(organization, app)

- if app.builds.count > 1
  %br
  %br
  %h2 All Builds
  %table.apps
    %tr
      %th File Name
      %th Upload Date
      %th Version
      %th 
    - app.builds.each do |build|
      %tr
        %td= link_to build.bundle.filename, organization_app_build_path(organization, app, build)
        %td= build.created_at.strftime("%m/%d/%Y %H:%M:%S")
        %td= build.version
        %td= link_to "Install", download_organization_app_build_path(organization, app, build)

app/views/builds/install.plist.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>items</key>
	<array>
		<dict>
			<key>assets</key>
			<array>
				<dict>
					<key>kind</key>
					<string>software-package</string>
					<key>url</key>
					<string><%= build.bundle.url.gsub(/localhost/, IP_ADDRESS) %></string>
				</dict>
			</array>
			<key>metadata</key>
			<dict>
				<key>bundle-identifier</key>
				<string><%=  build.bundle_identifier %></string>
				<key>bundle-version</key>
				<string><%= build.version %></string>
				<key>kind</key>
				<string>software</string>
				<key>subtitle</key>
				<string>Subtitle</string>
				<key>title</key>
				<string><%= build.display_name %></string>
			</dict>
		</dict>
	</array>
</dict>
</plist>

app/views/builds/new.html.haml
= form_for [app, build], :html => { :multipart => true } do |f|
  = f.label :bundle
  %small= f.error_message_on :bundle
  %small= f.error_message_on :bundle_identifier # this will display any corruption errors we find
  = f.file_field :bundle
  = f.submit 'Add Build'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title AppDispensary
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    %header
      %h1= link_to "AppDispensary", root_path
    %aside.flashes
      - %w(notice alert error success warning info).each do |flash_type|
        - if flash[flash_type.to_sym]
          %div.flash{:class => flash_type}
            = flash[flash_type.to_sym]
    
    %section.content= yield

app/views/organizations/index.html.haml
%h3.button= link_to 'Create new organization', new_organization_path

%ul
- organizations.each do |org|
  %li= link_to org.name, organization_path(org)

app/views/organizations/new.html.haml
= form_for organization do |f|
  = f.label :name
  %small= f.error_message_on :name
  = f.text_field :name
  = f.submit 'Create organization'

app/views/organizations/show.html.haml
%h3.button= link_to 'Create New Application', new_organization_app_path(organization)

- if organization.apps && organization.apps.count > 0
  %h2 Active Applications
  %table.apps
    %tr
      %th name
      %th
    - organization.apps.each do |app|
      %tr
        %td= link_to app.name, organization_app_path(organization, app)
        %td
          = link_to "Add Build", new_organization_app_build_path(organization, app)
          |
          - if app.latest_build
            = link_to "Latest Build", download_organization_app_build_path(organization, app, app.latest_build)
          - else
            No Builds
- else
  %h2 No Applications

app/views/welcome/index.html.haml
- if user_signed_in?
  %h3.button= link_to 'My Organizations', organizations_path
  %h3.button= link_to 'Sign Out', destroy_user_session_path
- else
  %h3.button= link_to 'Sign In', new_user_session_path